/**
 * RanchAssist™ Sprayer Calculator
 * Google Apps Script backend
 * Version 1.0.0
 *
 * Session-first architecture: this backend does not persist user project data.
 * Email sharing uses MailApp and receives only the summary the user explicitly sends.
 */

const RA_SPRAYER = Object.freeze({
  TOOL_ID: 'sprayer-calculator',
  TOOL_NAME: 'Sprayer Calculator',
  VERSION: '1.0.0'
});

function doGet() {
  const template = HtmlService.createTemplateFromFile('Index');
  template.runtimeConfig = JSON.stringify(getPublicRuntimeConfig_());

  return template.evaluate()
    .setTitle('Sprayer Calculator | RanchAssist')
    .setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL)
    .addMetaTag('viewport', 'width=device-width, initial-scale=1, viewport-fit=cover');
}

/**
 * Explicit allowlist of browser-safe runtime configuration.
 * Never return all Script Properties to the client.
 */
function getPublicRuntimeConfig_() {
  const props = PropertiesService.getScriptProperties();
  return {
    toolId: RA_SPRAYER.TOOL_ID,
    toolVersion: RA_SPRAYER.VERSION,
    supportEmail: props.getProperty('SUPPORT_EMAIL') || '',
    webAppUrl: ScriptApp.getService().getUrl() || ''
  };
}

/**
 * Sends a user-requested copy of the current Sprayer Calculator summary.
 * No API key is required; Apps Script MailApp handles delivery server-side.
 */
function sendSprayerSummary(payload) {
  payload = payload || {};
  const to = String(payload.to || '').trim();
  const subject = String(payload.subject || 'RanchAssist Sprayer Calculator Summary').trim().slice(0, 160);
  const plainText = String(payload.plainText || '').slice(0, 50000);

  if (!to || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(to)) {
    throw new Error('Enter a valid recipient email address.');
  }
  if (!plainText) {
    throw new Error('The summary is empty. Calculate a project before sharing it.');
  }

  const htmlBody = [
    '<div style="font-family:Arial,sans-serif;color:#171715;max-width:720px;margin:auto">',
    '<div style="font-size:12px;letter-spacing:.08em;text-transform:uppercase;color:#666660;margin-bottom:8px">RanchAssist™</div>',
    '<h1 style="font-size:26px;margin:0 0 12px">Sprayer Calculator</h1>',
    '<p style="font-size:14px;color:#666660;margin:0 0 20px">Field planning summary generated by the user.</p>',
    '<pre style="white-space:pre-wrap;font:14px/1.55 Arial,sans-serif;background:#F7F7F4;border:1px solid #DEDED8;border-radius:8px;padding:18px">',
    escapeHtml_(plainText),
    '</pre>',
    '<p style="font-size:12px;color:#666660;margin-top:20px"><strong>Application notice:</strong> The pesticide/herbicide label is the controlling source for legal rate, PPE, restrictions, re-entry, grazing/haying intervals, environmental precautions, and tank-mixing requirements. RanchAssist does not recommend products or off-label rates.</p>',
    '</div>'
  ].join('');

  MailApp.sendEmail({
    to: to,
    subject: subject || 'RanchAssist Sprayer Calculator Summary',
    body: plainText,
    htmlBody: htmlBody,
    name: 'RanchAssist'
  });

  return { ok: true, message: 'Summary emailed.' };
}

function escapeHtml_(value) {
  return String(value || '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}
